# Generated by Django 5.0.6 on 2024-07-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projects_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='comments',
            new_name='comment',
        ),
    ]
